-- SUPABASE DDL SCHEMA FOR PROPERTY MANAGEMENT SYSTEM (POSTGRESQL)
-- Copy and paste this script into your Supabase SQL Editor.

-- Drop existing tables if they exist
DROP TABLE IF EXISTS receipts CASCADE;
DROP TABLE IF EXISTS profits CASCADE;
DROP TABLE IF EXISTS budgets CASCADE;
DROP TABLE IF EXISTS expenses CASCADE;
DROP TABLE IF EXISTS bills CASCADE;
DROP TABLE IF EXISTS tenants CASCADE;
DROP TABLE IF EXISTS properties CASCADE;
DROP TABLE IF EXISTS admins CASCADE;

-- Drop existing types if they exist
DROP TYPE IF EXISTS admin_role CASCADE;
DROP TYPE IF EXISTS admin_status CASCADE;
DROP TYPE IF EXISTS property_type_enum CASCADE;
DROP TYPE IF EXISTS property_status_enum CASCADE;
DROP TYPE IF EXISTS tenant_status_enum CASCADE;
DROP TYPE IF EXISTS bill_status_enum CASCADE;
DROP TYPE IF EXISTS bill_language_enum CASCADE;
DROP TYPE IF EXISTS payment_method_enum CASCADE;
DROP TYPE IF EXISTS expense_payment_method_enum CASCADE;
DROP TYPE IF EXISTS receipt_status_enum CASCADE;

-- Create Enums
CREATE TYPE admin_role AS ENUM ('ADMIN', 'SUPER_ADMIN');
CREATE TYPE admin_status AS ENUM ('ACTIVE', 'INACTIVE');
CREATE TYPE property_type_enum AS ENUM ('APARTMENT', 'HOUSE', 'CONDO', 'STUDIO', 'OTHER');
CREATE TYPE property_status_enum AS ENUM ('AVAILABLE', 'OCCUPIED', 'MAINTENANCE', 'UNAVAILABLE');
CREATE TYPE tenant_status_enum AS ENUM ('ACTIVE', 'INACTIVE', 'EXPIRED', 'PENDING');
CREATE TYPE bill_status_enum AS ENUM ('PENDING', 'PAID', 'OVERDUE', 'RECEIPT_SENT', 'PARTIALLY_PAID', 'CANCELLED');
CREATE TYPE bill_language_enum AS ENUM ('en', 'fr');
CREATE TYPE payment_method_enum AS ENUM ('CARD', 'BANK_TRANSFER', 'CASH', 'CHECK', 'STRIPE', 'OTHER');
CREATE TYPE expense_payment_method_enum AS ENUM ('CARD', 'BANK_TRANSFER', 'CASH', 'CHECK', 'OTHER');
CREATE TYPE receipt_status_enum AS ENUM ('SENT', 'FAILED', 'PENDING');

-- Admins Table
CREATE TABLE admins (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role admin_role NOT NULL DEFAULT 'ADMIN',
  status admin_status NOT NULL DEFAULT 'ACTIVE',
  phone VARCHAR(50) DEFAULT NULL,
  avatar_url VARCHAR(500) DEFAULT NULL,
  two_factor_enabled BOOLEAN DEFAULT FALSE,
  two_factor_secret VARCHAR(255) DEFAULT NULL,
  two_factor_backup_codes TEXT DEFAULT NULL,
  last_login TIMESTAMP DEFAULT NULL,
  failed_login_attempts INT DEFAULT 0,
  locked_until TIMESTAMP DEFAULT NULL,
  created_by INT DEFAULT NULL REFERENCES admins(id) ON DELETE SET NULL,
  signature_photo VARCHAR(512) DEFAULT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Properties Table
CREATE TABLE properties (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id INT NOT NULL REFERENCES admins(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  description TEXT DEFAULT NULL,
  address VARCHAR(500) NOT NULL,
  city VARCHAR(100) NOT NULL,
  state VARCHAR(100) DEFAULT NULL,
  postal_code VARCHAR(20) NOT NULL,
  country VARCHAR(100) DEFAULT NULL,
  property_type property_type_enum NOT NULL DEFAULT 'APARTMENT',
  monthly_rent DECIMAL(10,2) DEFAULT NULL,
  photo VARCHAR(500) DEFAULT NULL,
  number_of_halls INT DEFAULT NULL,
  number_of_kitchens INT DEFAULT NULL,
  number_of_bathrooms INT DEFAULT NULL,
  number_of_parking_spaces INT DEFAULT NULL,
  number_of_rooms INT DEFAULT NULL,
  number_of_gardens INT DEFAULT NULL,
  square_meters DECIMAL(10,2) DEFAULT NULL,
  floor_number INT DEFAULT NULL,
  has_elevator BOOLEAN DEFAULT FALSE,
  has_balcony BOOLEAN DEFAULT FALSE,
  furnished BOOLEAN DEFAULT FALSE,
  available_from DATE DEFAULT NULL,
  status property_status_enum DEFAULT 'AVAILABLE',
  deleted_at TIMESTAMP WITH TIME ZONE DEFAULT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Tenants Table
CREATE TABLE tenants (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id INT NOT NULL REFERENCES admins(id) ON DELETE CASCADE,
  property_id INT NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) DEFAULT NULL,
  phone VARCHAR(50) DEFAULT NULL,
  lease_start DATE DEFAULT NULL,
  lease_end DATE DEFAULT NULL,
  rent_amount DECIMAL(10,2) DEFAULT NULL,
  join_date DATE NOT NULL,
  status tenant_status_enum NOT NULL DEFAULT 'ACTIVE',
  date_of_birth DATE DEFAULT NULL,
  deleted_at TIMESTAMP WITH TIME ZONE DEFAULT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Bills Table
CREATE TABLE bills (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id INT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  property_id INT NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
  admin_id INT NOT NULL REFERENCES admins(id) ON DELETE CASCADE,
  amount DECIMAL(10,2) NOT NULL,
  rent_amount DECIMAL(10,2) DEFAULT NULL,
  charges DECIMAL(10,2) DEFAULT 0.00,
  total_amount DECIMAL(10,2) DEFAULT NULL,
  month VARCHAR(7) NOT NULL,
  due_date DATE NOT NULL,
  status bill_status_enum NOT NULL DEFAULT 'PENDING',
  payment_date DATE DEFAULT NULL,
  description TEXT DEFAULT NULL,
  bill_date DATE NOT NULL,
  language bill_language_enum NOT NULL DEFAULT 'fr',
  pdf_path VARCHAR(500) DEFAULT NULL,
  bill_number VARCHAR(100) DEFAULT NULL UNIQUE,
  payment_method payment_method_enum DEFAULT NULL,
  reminder_sent BOOLEAN DEFAULT FALSE,
  reminder_count INT DEFAULT 0,
  last_reminder_date DATE DEFAULT NULL,
  deleted_at TIMESTAMP WITH TIME ZONE DEFAULT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UNIQUE(tenant_id, month)
);

-- Expenses Table
CREATE TABLE expenses (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  property_id INT DEFAULT NULL REFERENCES properties(id) ON DELETE CASCADE,
  admin_id INT NOT NULL REFERENCES admins(id) ON DELETE CASCADE,
  month VARCHAR(7) NOT NULL,
  category VARCHAR(100) NOT NULL,
  amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  notes TEXT DEFAULT NULL,
  description VARCHAR(500) DEFAULT NULL,
  invoice_number VARCHAR(100) DEFAULT NULL,
  invoice_date DATE DEFAULT NULL,
  vendor_name VARCHAR(255) DEFAULT NULL,
  payment_method expense_payment_method_enum DEFAULT NULL,
  receipt_path VARCHAR(500) DEFAULT NULL,
  deleted_at TIMESTAMP WITH TIME ZONE DEFAULT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Budgets Table
CREATE TABLE budgets (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  property_id INT NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
  month VARCHAR(7) NOT NULL,
  budgeted_income DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  budgeted_expenses DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  actual_income DECIMAL(12,2) DEFAULT 0.00,
  actual_expenses DECIMAL(12,2) DEFAULT 0.00,
  notes TEXT DEFAULT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UNIQUE(property_id, month)
);

-- Profits Table
CREATE TABLE profits (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id INT NOT NULL REFERENCES admins(id) ON DELETE CASCADE,
  total_profit DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  last_updated TIMESTAMP WITH TIME ZONE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Receipts Table
CREATE TABLE receipts (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bill_id INT NOT NULL REFERENCES bills(id) ON DELETE CASCADE,
  tenant_id INT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  admin_id INT NOT NULL REFERENCES admins(id) ON DELETE CASCADE,
  sent_date TIMESTAMP WITH TIME ZONE NOT NULL,
  sent_to_tenant BOOLEAN NOT NULL DEFAULT TRUE,
  sent_to_admin BOOLEAN NOT NULL DEFAULT TRUE,
  sent_to_owner BOOLEAN NOT NULL DEFAULT FALSE,
  tenant_email VARCHAR(255) DEFAULT NULL,
  admin_email VARCHAR(255) DEFAULT NULL,
  owner_email VARCHAR(255) DEFAULT NULL,
  pdf_path VARCHAR(500) DEFAULT NULL,
  status receipt_status_enum NOT NULL DEFAULT 'PENDING',
  error_message TEXT DEFAULT NULL,
  receipt_number VARCHAR(100) DEFAULT NULL UNIQUE,
  retry_count INT DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Create trigger functions to automatically update the updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ language 'plpgsql';

-- Attach update triggers to all tables
CREATE TRIGGER update_admins_updated_at BEFORE UPDATE ON admins FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_properties_updated_at BEFORE UPDATE ON properties FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_tenants_updated_at BEFORE UPDATE ON tenants FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_bills_updated_at BEFORE UPDATE ON bills FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_expenses_updated_at BEFORE UPDATE ON expenses FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_budgets_updated_at BEFORE UPDATE ON budgets FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_profits_updated_at BEFORE UPDATE ON profits FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_receipts_updated_at BEFORE UPDATE ON receipts FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- Seed default initial admin (Mohamed Rahim)
-- Note: Password is bcrypt hash for 'admin123'
INSERT INTO admins (name, email, password, role, status)
VALUES ('Mohamed Rahim', 'rahim@property.com', '$2a$12$zOYFzwB0Cf/P4p95MDb33eGSc2nX3sMjFHU6RUbMVa4GY.IPtk9Qi', 'SUPER_ADMIN', 'ACTIVE')
ON CONFLICT (email) DO NOTHING;
